### ISSUE TITLE
Details about training the best single model described in the paper

### ISSUE THREAD

**Issue by gurunathparasaram** [zhawe01/fairseq-gec#11]
In the Copynet paper, in `Table-5: Single Model ablation study`, it is mentioned that F-score for  the copy-augmented transformer architecture with the denoising auto-encoder(pre-trained) is 58.80. 
- I tried downloading the code, pre-trained models and the data you have provided in the repo and got an F-score of 52.76
- Does the current repo with the given `train.sh`, pre-trained model file: `checkpoint9.pt` and  data provided in the download link replicate the result of 58.8 F-score with 9 epochs as mentioned in the train.sh script?
- Should we change any of the hyper-parameters to achieve the F-score of 58.8 mentioned in the paper?

Thanks.

**Comment by zhawe01** [comment]
Please check the following three things.
1. The pre-trained model was loaded during training and you can check the log. 
2. You use the generate.sh script to get the evaluation result.
3. You use the spell corrected source file.
