### ISSUE TITLE
How to make training data.

### ISSUE THREAD

**Issue by ghost** [zhawe01/fairseq-gec#14]
Thank you for your excellent job of the GEC task.  I am troubled with preprocessing of training data.
Please tell me how to preprocess training data. Specifically, I want to know how to make training data.

**Comment by zhawe01** [comment]
Please refer to the "pre-processed data", where I shared the training data.

**Comment by ghost** [comment]
Thank you for your reply. I want to know how you made training data from Lang8.

**Comment by zhawe01** [comment]
A few steps:
1. remove unchanged sentence pairs.
2. clean the dataset by removing some noise pairs with a few rules.
3. tokenize.

**Comment by ghost** [comment]
I understand 1 step and 3 step . I have a question about 2 steps . Can you tell me about a few rules .

**Comment by zhawe01** [comment]
1. remove pairs that has no difference with each other.
2. remove pairs that the length difference of the src and tgt sentence is big.
3. remove pairs with few normal tokens.
......
