### ISSUE TITLE
Some problems about run pretrain.sh

### ISSUE THREAD

**Issue by cibiluozu** [zhawe01/fairseq-gec#17]
Hello, I want to use _subtoken_ instead of the original _token_ to modify this code, and then after generating training data, the following error occurred when running the code pretrain.sh. 

> Exception: process 1 terminated with signal SIGKILL

Have you had any similar error? And how much memory did you use when you ran 100 million data?

**Comment by cibiluozu** [comment]
![image](https://user-images.githubusercontent.com/10922425/62200564-45ec9e00-b3b8-11e9-820d-99686abe660f.png)
The code has some problems when it comes to big data.

**Comment by zhawe01** [comment]
Yes, it needs a lot of memory if you try to load a big corpus. We use a machine of 250G memory.
