### ISSUE TITLE
About the model performance

### ISSUE THREAD

**Issue by EdwardZH** [zhawe01/fairseq-gec#20]
I have tried this code without pretrain and the performance is presented as follow:
P:0.6580  R:0.2570  F0.5:0.5015
However, I find the paper report this performance should be about 54(Transformer + Copy).

**Comment by EdwardZH** [comment]
And I train this model with 2 gpus and 15 epochs

**Comment by zhawe01** [comment]
More epochs are needed without pre-training. Try 30 epochs.

**Comment by EdwardZH** [comment]
Sure, the pretrained model also needs more epochs?

**Comment by zhawe01** [comment]
Fine-tuning 10 epochs is enough with pre-training parameters.

**Comment by EdwardZH** [comment]
Thank you very much! The results are  0.5937 and 0.5428, respectively.

**Comment by jwc19890114** [comment]
> I have tried this code without pretrain and the performance is presented as follow:
> P:0.6580 R:0.2570 F0.5:0.5015
> However, I find the paper report this performance should be about 54(Transformer + Copy).

Does this program work? I cannot initialize the pre-trained model, how to use it? T_T

**Comment by ghost** [comment]
> I have tried this code without pretrain and the performance is presented as follow:
> P:0.6580 R:0.2570 F0.5:0.5015
> However, I find the paper report this performance should be about 54(Transformer + Copy).



> I have tried this code without pretrain and the performance is presented as follow:
> P:0.6580 R:0.2570 F0.5:0.5015
> However, I find the paper report this performance should be about 54(Transformer + Copy).

Hello,  may I ask how many epoch you have trained to get the performance which F0.5 is 0.5015 ?
I tried 15 epoches, but F0.5 only reaches around 0.36.
