### ISSUE TITLE
Multi-Task

### ISSUE THREAD

**Issue by GrowingZBF** [zhawe01/fairseq-gec#24]
Hello~ We are so interested in this paper's thoughts, while we cannot find the code of multi-task, and if you will release this code next~

**Comment by GrowingZBF** [comment]
And in your paper, there is a context of MTL that "When inputting the right sentences,we remove the decoder’s attention over the outputs of the encoder. Without the encoder-decoder attention, the generating work gets hard.". How to check if the inputting sentences are right or not here?

**Comment by zhawe01** [comment]
We have no plan to reorganize the multi-task part, but if you are interested, I can provide the details.

In the paper, we mentioned that the right sentences come from Wikipedia, and we assume these sentences are correct.

**Comment by GrowingZBF** [comment]
So thanks for your reply~  
As for the sentence-level, my understanding is that you put lots sentences into the model in training process, and sentences from wiki are assumed as right while others are assumed as wrong. Is it right?

**Comment by zhawe01** [comment]
Yes.
