### ISSUE TITLE
Cross entropy loss giving RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Deepayan137** [zhawe01/fairseq-gec#26]
Hi,

I tried to train a model from scratch on the data that I have downloaded from the link mentioned on your readme. However, when I am trying to train the model I am facing a runtime error.  The issue I think is perhaps due to the format of data because when I tried to run the same code on a different dataset (eng-german), the code seems to run without any glitch. 
Currently, I am using python 3.7 and pytorch version 1.3.
Any help would be deeply appreciated.

**Comment by soyoung97** [comment]
Hi,
I am currently facing the opposite problem - training the model (by the instruction provided with readme) using dataset provided work without any glitch, but when I try it with different dataset, it doesn't work.
Can you tell me more specifically about how you made the code working with different dataset(eng-german)? what file did you put in the out folder? which were the formats? did you make data/train_merge.src?
It will be very helpful if you give me any information.

**Comment by zhawe01** [comment]
If you want to run a translation dataset, I suggest you use the fairseq code. Different with fairseq, fairseq-gec contains copy mechanism and edit-weighted loss, and both of them are not so useful when you do the translation.

**Comment by saiprasanth385** [comment]
Hi,
I am getting the same "CUDA error: device-side assert triggered" error when I tried to run the train.sh by interchanging src and target inside out/data_bin.
I used CUDA_LAUNCH_BLOCKING=1 to pinpoint the problem and this is what I found.
"RuntimeError: cuda runtime error (59) : device-side assert triggered at /pytorch/aten/src/THC/generic/THCTensorScatterGather.cu:293"
