### ISSUE TITLE
Where is "g.sh"?

### ISSUE THREAD

**Issue by jimbozhang** [zhawe01/fairseq-gec#30]
According README.md, for evaluating on the CoNLL-2014 testset, it should run the following script:

`sh g.sh \${device_id} \${experiment_name}`

But, where is the "g.sh"?? I don't find it in this repository.

**Comment by Chhokra** [comment]
Did you find it? I see that you've closed it

**Comment by zhawe01** [comment]
It's generate.sh.

**Comment by Chhokra** [comment]
> It's generate.sh.

I wanted to know how can I find myy gpu device id? Thank you
