### ISSUE TITLE
question about the sentences copy task

### ISSUE THREAD

**Issue by wangwang110** [zhawe01/fairseq-gec#7]
First，thank you for your good work，I want to know， in  sentence-copy task，how to construct one batch， half of the correct sentence pairs and half of the edited sentence pairs？ or one batch only containing the correct sentence pairs and the next batch only containing the edited sentence pairs

**Comment by wangwang110** [comment]
and if don‘t use attention， which output will be considered as the input of decoder part？

**Comment by zhawe01** [comment]
One batch only containing the correct sentence pairs and the next batch only containing the edited sentence pairs.

**Comment by zhawe01** [comment]
There are two attentions in the model. One is the encoder-decoder attention and the other is the copying attention. We only disable the encoder-decoder attention.

**Comment by wangwang110** [comment]
> There are two attentions in the model. One is the encoder-decoder attention and the other is the copying attention. We only disable the encoder-decoder attention.

ok，I got，thank you very much
