### ISSUE TITLE
Question about evaluation?

### ISSUE THREAD

**Issue by liusiyi641** [zhawe01/fairseq-gec#8]
Can I do the evaluations without any training? If so, where can I find the script g.sh? Or do I have to train it with the pre-trained model first and then it will generate a g.sh script? Or do I have to create a g.sh script myself by calling some of the scripts? Thank you for the gracious help!

**Comment by liusiyi641** [comment]
And by the way, what does the device_id and experiment_name parameter mean?

**Comment by liusiyi641** [comment]
Or does the g.sh refer to generate.sh?

**Comment by zhawe01** [comment]
g.sh refer to generate.sh.
device_id means which GPU device you want to use.
experiment_name is a name that you give to the result folder and you can name it whatever you like.

**Comment by danielwonght** [comment]
Running generate.sh shows "No such file or directory: './data/test.m2 ". When does the script creates the this file?

**Comment by Chhokra** [comment]
How does one find GPU device id?
